### ISSUE TITLE
支持定制化环境吗

### ISSUE THREAD

**Issue by JaveleyQAQ** [Mustard404/AceofHearts#1]

**Comment by Mustard404** [comment]
可以提需求，按照环境去添加增量工具包

**Comment by JaveleyQAQ** [comment]
推荐两个chrome插件
https://chrome.google.com/webstore/detail/immersive-translate/bpoadfkcbjbfhfodiogcnhhhpibjhbnh?hl=zh-CN
https://github.com/dark-kingA/superSearchPlus

**Comment by Mustard404** [comment]
第一个插件为翻译插件，与项目关联不是很大；
第二个插件未在Chrome 商店发布，无法通过脚本的方式进行部署；
