### ISSUE TITLE
navicat下载出错及一些建议。

### ISSUE THREAD

**Issue by vstVV** [Mustard404/AceofHearts#2]
1. 部分工具下载超时后直接就退出了，建议**增加** 选择是否**跳过后继续**， 的功能，目前安装到navicat会出现超时错误：

`下载失败：Get "https://download.navicat.com.cn/download/navicat162_premium_cs_x64.exe": net/http: TLS handshake`

1. 另外 Github api 那里建议填写一次以后保存到本地，失败后重新开始可以自动获取，不需要每次都重新填写一遍。

1. 最后，很好很方便的项目，希望继续优化。加油！感谢作者的付出！

**Comment by Mustard404** [comment]
已经按照建议修改：
1. 优化Github Api方式，将原来终端输入改为读取配置文件（config.ini）。
2. 解决Navicat下载出现ssl错误，修改为HTTP协议。
